---
- name: "Create web group"
  group:
    name: webdeploy
    state: present

- name: "Create deploy user"
  user:
    name: "{{ deploy_user }}"
    createhome: no
    groups: webdeploy
    state: present

- name: "Put users in group"
  user:
    name: "{{ item }}"
    groups: webdeploy
  with_items: 
   - ubuntu
   - jamesdoc
   - "{{ deploy_user }}"
