---
- name: "Make sure folders are there"
  file:
    path: "{{ live_location }}/{{ item }}"
    state: directory
  with_items:
    - /tmp/sockets
    - /tmp/pids

- name: "Kill all running puma instances"
  shell: ps -aux | grep puma | grep -v grep | awk  '{print $2}' | xargs kill -9

- name: "Turn it on"
  shell: bundle exec puma -e production -d -b unix://./tmp/sockets/puma.sock --pidfile ./tmp/pids/puma.pid
  args:
    chdir: "{{ live_location }}"

- name: "Wipe out nginx cache"
  file:
    path: "{{ nginx_cache }}"
    state: absent

- name: restart nginx
  service: name=nginx state=restarted
