# Server setup
locale: en_GB.UTF-8
timezone: Europe/London

# Ruby
ruby_install_version: 0.6.1
ruby_version: 2.3.3

deploy_user: deploy
web_directory: /srv/tgc
live_location: "{{ web_directory }}/live"
uploads_location: "{{ web_directory }}/uploads"

releases_to_keep: 5

nginx_cache: /tmp/nginx_cache
globe_cache_location: "{{ nginx_cache }}/tgc"
