---
- name: "Install web server software"
  apt: pkg={{ item }} state=installed
  with_items:
  - nginx

- name: "Remove default setup"
  file:
    state: absent
    path: "/etc/nginx/sites-available/default"

- name: "(Re)start Nginx"
  service:
    name: nginx
    state: restarted
