---
- name: Setup server
  hosts: all
  become: true # become sudo
  gather_facts: False
  pre_tasks:
    - name: "apt-get update"
      raw: apt-get update -qq
    - name: "apt-get upgrade"
      raw: apt-get upgrade -qq
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    - setup: # aka gather_facts
  tasks:
    - name: "Wipe out nginx cache"
      file:
        path: "{{ nginx_cache }}"
        state: absent

    - name: restart nginx
      service: name=nginx state=restarted
