---
- name: Creates deploy dir
  file:
    path: "{{ deploy_location }}"
    state: directory
    owner: ubuntu
    group: webdeploy
    mode: 0775

- name: "Clone the repo"
  become: false
  git:
    repo: 'https://github.com/theglobechurch/tgc.git'
    dest: "{{ deploy_location }}"
    force: yes

- name: "Add devise key"
  become: false
  lineinfile:
    dest: ~/.profile
    state: present
    regexp: '^DEVISE_SECRET_KEY'
    line: "DEVISE_SECRET_KEY='{{ lookup('password', 'creds/devise_sk.txt length=64 chars=ascii_letters,digits,hexdigits') }}'"

- name: "Add rails key"
  become: false
  lineinfile:
    dest: ~/.profile
    state: present
    regexp: '^RAILS_SECRET_KEY'
    line: "RAILS_SECRET_KEY='{{ lookup('password', 'creds/rails_sk.txt length=64 chars=ascii_letters,digits,hexdigits') }}'"

- name: "Install Gems"
  become: false
  bundler:
    state: present
    gemfile: "{{ deploy_location }}Gemfile"

- name: "NPM install"
  become: false
  npm:
    path: "{{ deploy_location }}"

- name: "Setup database"
  become: false
  shell: bundle exec rake db:migrate RAILS_ENV="production" 
  args:
    chdir: "{{ deploy_location }}"

- name: "Seed database"
  become: false
  shell: bundle exec rake db:seed
  args:
    chdir: "{{ deploy_location }}"

- name: "Gulp all the things"
  become: false
  shell: node_modules/.bin/gulp deploy
  args:
    chdir: "{{ deploy_location }}"

- name: "Precompile assets"
  become: false
  shell: bundle exec rails assets:precompile RAILS_ENV="production" 
  args:
    chdir: "{{ deploy_location }}"
